export enum ERROR_CODES {
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_UNAUTHORIZED = "USER_UNAUTHORIZED",
  USER_FORBIDDEN = "USER_FORBIDDEN",

  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  TOKEN_INVALID = "TOKEN_INVALID",
  ACCESS_DENIED = "ACCESS_DENIED",

  INVALID_REFRESH_TOKEN_SECRET = "INVALID_REFRESH_TOKEN_SECRET",
  INVALID_JWT_SECRET = "INVALID_JWT_SECRET",

  VALIDATION_ERROR = "VALIDATION_ERROR",
  MISSING_FIELDS = "MISSING_FIELDS",
  INVALID_FORMAT = "INVALID_FORMAT",
  OUT_OF_RANGE = "OUT_OF_RANGE",

  DB_CONNECTION_ERROR = "DB_CONNECTION_ERROR",
  DB_QUERY_FAILED = "DB_QUERY_FAILED",
  DB_DUPLICATE_ENTRY = "DB_DUPLICATE_ENTRY",

  FILE_TOO_LARGE = "FILE_TOO_LARGE",
  UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE",
  FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED",

  BAD_REQUEST = "BAD_REQUEST",
  NOT_FOUND = "NOT_FOUND",
  METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",

  INTERNAL_ERROR = "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT",

  EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR",
  THIRD_PARTY_API_ERROR = "THIRD_PARTY_API_ERROR",
  PAYMENT_FAILED = "PAYMENT_FAILED",
}
